apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kepler-orbit

resources:
  - ../../../base/kepler-orbit
  - namespace.yaml

images:
  - name: ghcr.io/incognito124/kepler-orbit
    newTag: "1767736178"
