services:
  blog:
    container_name: personal-blog
    image: "{{ frontendDockerImage }}"
    restart: always
    environment:
      BLOG_DB: 'blog-db:80'
    ports:
      - 3000:3000
  blog-db:
    container_name: blog-db
    image: "{{ dbDockerImage }}"
    restart: always