# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-traefik
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./cosmos/clusters/prod/apps/monitoring/traefik
  interval: 1m
  timeout: 2m
  retryInterval: 1m
  wait: true
  prune: true
  dependsOn:
    - name: monitoring
  targetNamespace: monitoring