apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal-website

resources:
  - ../../../base/personal-website
  - namespace.yaml



images:
  - name: ghcr.io/incognito124/personal-website
    newTag: "1767736178"
