apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brachi

resources:
  - ../../../base/brachi
  - namespace.yaml

images:
  - name: ghcr.io/incognito124/brachi
    newTag: "1767733870"
