apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    traefik.ingress.kubernetes.io/router.middlewares: "argocd-redirect-https@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - host: msmetko.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website
                port:
                  number: 80
