apiVersion: apps/v1
kind: Deployment
metadata:
  name: brachi
  labels:
    app: brachi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brachi
  template:
    metadata:
      labels:
        app: brachi
    spec:
      containers:
        - name: brachi
          image: ghcr.io/incognito124/brachi:latest
          ports:
            - name: web
              containerPort: 80
