apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal-website-staging

resources:
- ../../../base/personal-website/
- namespace.yaml

patches:
- target:
    kind: Ingress
    name: personal-website
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: msmetko.xyz.test
