[package]
name = "rustsampler"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.10.0"
rand_distr = "0.6.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tqdm = "0.8.0"

[dev-dependencies]
tqdm = "0.8.0"
