services:
  blog:
    container_name: personal-blog
    image: ghcr.io/incognito124/personal-blog-frontend:1754170764
    restart: always
    environment:
      BLOG_DB: 'blog-db:80'
  blog-db:
    container_name: blog-db
    image: ghcr.io/incognito124/personal-blog-database:1753996488
    restart: always
