services:
  blog:
    container_name: personal-blog
    image: ghcr.io/incognito124/personal-blog-frontend:1762104408
    restart: always
    environment:
      BLOG_DB: 'blog-db:80'
    ports:
      - 3000:3000
  blog-db:
    container_name: blog-db
    image: ghcr.io/incognito124/personal-blog-database:1762103202
    restart: always
