---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.msmetko.xyz`)
    kind: Rule
    services:
    - name: monitoring-kube-prometheus-stack-grafana
      port: 80
  tls:
    certResolver: letsencrypt

