apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal-blog

resources:
  - ../../../base/personal-blog
  - namespace.yaml

images:
  - name: ghcr.io/incognito124/personal-blog-frontend
    newTag: "1767736178"
  - name: ghcr.io/incognito124/personal-blog-database
    newTag: "1767733870"
