[project]
name = "cosmos"
version = "0.1.0"
description = "Production universe of @InCogNiTo124 (powered by Hetzner and Pulumi)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pulumi==3.214.0",
    "pulumi-hcloud==1.29.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
