name: "Moon (PR to main)"
on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      targets:
        description: "Targets to run"
        required: false
        default: ""
        type: string

jobs:
  ci:
    name: "CI"
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up musl
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-dev musl-tools

      - name: "Setup wasm-pack"
        env:
          WASM_PACK_VERSION: "v0.13.1"
        run: |
          curl -LO https://github.com/drager/wasm-pack/releases/download/${{ env.WASM_PACK_VERSION }}/wasm-pack-${{ env.WASM_PACK_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          tar xvzf wasm-pack-${{ env.WASM_PACK_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          sudo cp wasm-pack-${{ env.WASM_PACK_VERSION }}-x86_64-unknown-linux-musl/wasm-pack /usr/bin

      - uses: "actions/checkout@main"
        with:
          fetch-depth: 0

      - uses: "moonrepo/setup-toolchain@v0"
        with:
          auto-setup: true
          cache: false # i don't care, install all tools fresh

      - name: Install uv
        run: |
          UV_VERSION=$(grep -A 2 "uv:" .moon/toolchain.yml | grep "version:" | cut -d '"' -f 2)
          proto install uv $UV_VERSION

      - run:
          "moon ${{ github.event.inputs.targets && github.event.inputs.targets
          || 'ci'}}"
        env:
          RUSTUP_AUTO_INSTALL: 0

      - uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Collect/retrospect on results"
        uses: "appthrust/moon-ci-retrospect@main"
        if: always()
