name: Pulumi (push to main)
on:
  push:
    branches:
      - main

jobs:
  preview:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: astral-sh/setup-uv@main

      # pulumi actions don't seem to work with uv without this
      # https://github.com/pulumi/actions/issues/1117#issuecomment-2784766954
      - run: uv --project=cosmos sync
      - uses: pulumi/actions@main
        with:
          command: up
          stack-name: cosmos
          work-dir: ./cosmos 
          comment-on-summary: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          ARIES_PUB: ${{ secrets.ARIES_PUB }}
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          PULUMI_SKIP_CONFIRMATIONS: 'true'
