name: Pulumi (PR to main)
on:
  pull_request:
  workflow_dispatch:
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: astral-sh/setup-uv@main

      # pulumi actions don't seem to work with uv without this
      # https://github.com/pulumi/actions/issues/1117#issuecomment-2784766954
      - run: uv --project=cosmos sync 
      - uses: pulumi/actions@main
        with:
          command: preview
          stack-name: cosmos
          work-dir: ./cosmos
          comment-on-pr: true
          comment-on-summary: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          ARIES_PUB: ${{ secrets.ARIES_PUB }}
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          PULUMI_SKIP_CONFIRMATIONS: 'true'

